name: Build
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r11c

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Restore Previous Cache
        if: ${{ always() }}
        id: cache-final-build-android-restore
        uses: actions/cache/restore@main
        with:
          path: |
            ~/haxelib
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git
          haxelib install flixel-addons 3.2.0 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel 5.3.1 --quiet
          haxelib install SScript 6.1.80 --quiet
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
          haxelib install lime 7.9.0 --quiet
          haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit.git
          haxelib install openfl 9.2.1 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib git extension-orientation https://github.com/HaxeExtension/extension-orientation.git
          haxelib install hxCodec 3.0.2 --quiet

      - name: Setup git hxcpp
        run: |
          cd $(haxelib libpath hxcpp)/tools/hxcpp
          haxe compile.hxml
          cd ${{ github.workspace }}

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build android -arm64 -final
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni

      - name: Clear Previous Cache
        if: ${{ always() }}
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-android-build") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Save Current Cache
        if: ${{ always() }}
        id: cache-final-build-android-save
        uses: actions/cache/save@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
  Windows:
    runs-on: windows-2019
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Restore Previous Cache
        if: ${{ always() }}
        id: cache-final-build-windows-restore
        uses: actions/cache/restore@main
        with:
          path: |
            C:\haxelib
            export\release\windows\haxe
            export\release\windows\obj
          key: cache-windows-build

      - name: Install Libraries
        run: |
          haxelib setup C:\haxelib
          haxelib install flixel-addons 3.2.0 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel 5.3.1 --quiet
          haxelib install SScript 6.1.80 --quiet
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
          haxelib install lime 7.9.0 --quiet
          haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit.git
          haxelib install openfl 9.2.1 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib install hxCodec 3.0.2 --quiet

      - name: Setup git hxcpp
        run: |
          cd C:\haxelib\hxcpp\git\tools\hxcpp
          haxe compile.hxml
          cd ${{ github.workspace }}

      - name: Compile
        run: haxelib run lime build windows -64 -final

      - name: Clear Previous Cache
        if: ${{ always() }}
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-windows-build") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Save Current Cache
        if: ${{ always() }}
        id: cache-final-build-windows-save
        uses: actions/cache/save@main
        with:
          path: |
            C:\haxelib
            export\release\windows\haxe
            export\release\windows\obj
          key: cache-windows-build

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export\release\windows\bin
          if-no-files-found: error
  Linux:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Restore Previous Cache
        if: ${{ always() }}
        id: cache-final-build-linux-restore
        uses: actions/cache/restore@main
        with:
          path: |
            ~/haxelib
            export/release/linux/haxe
            export/release/linux/obj
          key: cache-linux-build

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install flixel-addons 3.2.0 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel 5.3.1 --quiet
          haxelib install SScript 6.1.80 --quiet
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
          haxelib install lime 7.9.0 --quiet
          haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit.git
          haxelib install openfl 9.2.1 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib install hxCodec 3.0.2 --quiet

      - name: Setup git hxcpp
        run: |
          cd $(haxelib libpath hxcpp)/tools/hxcpp
          haxe compile.hxml
          cd ${{ github.workspace }}

      - name: Compile
        run: haxelib run lime build linux -64 -final

      - name: Clear Previous Cache
        if: ${{ always() }}
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-linux-build") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Save Current Cache
        if: ${{ always() }}
        id: cache-final-build-linux-save
        uses: actions/cache/save@main
        with:
          path: |
            ~/haxelib
            export/release/linux/haxe
            export/release/linux/obj
          key: cache-linux-build

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: export/release/linux/bin
          if-no-files-found: error
  MacOS:
    runs-on: macos-${{ matrix.osversion }}
    strategy:
      matrix:
        osversion: [11, 12, 13]
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Restore Previous Cache
        if: ${{ always() }}
        id: cache-final-build-macos-restore
        uses: actions/cache/restore@main
        with:
          path: |
            ~/haxelib
            export/release/macos/haxe
            export/release/macos/obj
          key: cache-macos${{ matrix.osversion }}-build

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install flixel-addons 3.2.0 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel 5.3.1 --quiet
          haxelib install SScript 6.1.80 --quiet
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
          haxelib install lime 7.9.0 --quiet
          haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit.git
          haxelib install openfl 9.2.1 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib install hxCodec 3.0.2 --quiet

      - name: Setup git hxcpp
        run: |
          cd $(haxelib libpath hxcpp)/tools/hxcpp
          haxe compile.hxml
          cd ${{ github.workspace }}

      - name: Compile
        run: haxelib run lime build mac -64 -final

      - name: Clear Previous Cache
        if: ${{ always() }}
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-macos-build") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Save Current Cache
        if: ${{ always() }}
        id: cache-final-build-macos-save
        uses: actions/cache/save@main
        with:
          path: |
            ~/haxelib
            export/release/macos/haxe
            export/release/macos/obj
          key: cache-macos${{ matrix.osversion }}-build

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: macos${{ matrix.osversion }}Build
          path: export/release/macos/bin
          if-no-files-found: error 
